export const styles = {
  container: {
    minHeight: "100vh",
    background: "linear-gradient(135deg, #0a0f1a 0%, #111827 100%)",
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    color: "#f1f5f9",
  },
  wrapper: {
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "48px 16px",
    position: "relative",
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 16px",
    borderRadius: "9999px",
    background: "rgba(45, 212, 191, 0.1)",
    border: "1px solid rgba(45, 212, 191, 0.2)",
    color: "#2dd4bf",
    fontSize: "14px",
    fontWeight: "500",
    marginBottom: "24px",
  },
  header: {
    textAlign: "center",
    marginBottom: "48px",
  },
  title: {
    fontSize: "clamp(2rem, 5vw, 3rem)",
    fontWeight: "700",
    marginBottom: "16px",
  },
  titleGradient: {
    background: "linear-gradient(135deg, #2dd4bf, #a78bfa)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
  },
  subtitle: {
    fontSize: "18px",
    color: "#94a3b8",
    maxWidth: "600px",
    margin: "0 auto",
  },
  card: {
    background: "rgba(30, 41, 59, 0.5)",
    backdropFilter: "blur(20px)",
    border: "1px solid rgba(71, 85, 105, 0.3)",
    borderRadius: "16px",
    overflow: "hidden",
  },
  uploadCard: {
    padding: "32px",
    border: "2px dashed rgba(71, 85, 105, 0.5)",
    cursor: "pointer",
    transition: "all 0.3s ease",
  },
  uploadIcon: {
    width: "64px",
    height: "64px",
    borderRadius: "50%",
    background: "rgba(45, 212, 191, 0.1)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 16px",
  },
  button: {
    padding: "12px 24px",
    background: "#2dd4bf",
    color: "#0a0f1a",
    fontWeight: "600",
    borderRadius: "12px",
    border: "none",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "14px",
    transition: "all 0.2s ease",
    boxShadow: "0 4px 20px rgba(45, 212, 191, 0.25)",
  },
  buttonSecondary: {
    padding: "8px 16px",
    background: "rgba(51, 65, 85, 0.5)",
    color: "#f1f5f9",
    fontWeight: "500",
    borderRadius: "8px",
    border: "none",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "14px",
  },
  table: {
    width: "100%",
    fontSize: "14px",
    borderCollapse: "collapse",
  },
  th: {
    padding: "12px 16px",
    textAlign: "left",
    fontWeight: "600",
    color: "#94a3b8",
    textTransform: "uppercase",
    fontSize: "12px",
    letterSpacing: "0.05em",
    background: "rgba(51, 65, 85, 0.3)",
  },
  td: {
    padding: "12px 16px",
    borderBottom: "1px solid rgba(71, 85, 105, 0.3)",
  },
  tag: {
    padding: "4px 8px",
    borderRadius: "6px",
    fontSize: "12px",
    fontWeight: "600",
  },
  statCard: {
    padding: "24px",
    background: "rgba(30, 41, 59, 0.5)",
    backdropFilter: "blur(20px)",
    border: "1px solid rgba(71, 85, 105, 0.3)",
    borderRadius: "16px",
  },
  statIcon: {
    width: "40px",
    height: "40px",
    borderRadius: "8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  mono: {
    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
  },
  success: { color: "#22c55e" },
  danger: { color: "#ef4444" },
  successBg: { background: "rgba(34, 197, 94, 0.2)", color: "#22c55e" },
  dangerBg: { background: "rgba(239, 68, 68, 0.2)", color: "#ef4444" },
  accentBg: { background: "rgba(167, 139, 250, 0.2)", color: "#a78bfa" },
  primaryBg: { background: "rgba(45, 212, 191, 0.2)", color: "#2dd4bf" },
  mutedBg: { background: "rgba(51, 65, 85, 0.5)", color: "#94a3b8" },
};